name: Build and publish docker image to Azure

on:
  # In order to use this workflow, replace `<application name>` with name of your app and add secrets
  workflow_dispatch:
  # workflow_run:
  #   workflows: ['Build project', 'Run unit tests']
  #   types:
  #     - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/<application name>:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/<application name>:${{ github.sha }}
