name: Build test and deploy

on:
  # In order to use this workflow, replace `$APPLICATION_NAME` with name of your app and add secrets
  workflow_dispatch:
  #workflow_run:
  # workflows: ['Build project', 'Run unit tests']
  # types:
  #   - completed

env:
  APPLICATION_NAME: <set me>

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn install && yarn build

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        run: |
          yarn install && yarn test

  build-and-push-docker-image:
    runs-on: ubuntu-latest

    needs: test
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/$APPLICATION_NAME:${{ github.sha }}
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/$APPLICATION_NAME:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest

    environment: staging
    needs: build-and-push-docker-image
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.AZURE_RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ env.APPLICATION_NAME }}:${{ github.sha }}
          registry-login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          name: ${{ env.APPLICATION_NAME }}
          location: 'westeurope'
