name: Generate Swagger JSON

on:
  workflow_dispatch: # If you want to create Swagger docs, replace this line with commented out code below.
  #  push:
  #    branches:
  #      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Swagger JSON
        run: mkdir -p ./swagger && yarn swagger:generate

      - name: Create Directory for Deployment
        run: mkdir -p ./publish

      - name: Copy Swagger JSON to Publish Directory
        run: cp swagger/swagger.json ./publish/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
